import { Dice } from '@/utils/dice'

export const heroDiceMap: Record<string, Dice[]> = {
  // Young_Blood: [
  //   { diceType: 'Strength', diceSides: 8 },
  //   { diceType: 'Strength', diceSides: 6 },
  //   { diceType: 'Strength', diceSides: 4 },
  //   { diceType: 'Agility', diceSides: 6 },
  //   { diceType: 'Agility', diceSides: 4 },
  //   { diceType: 'Agility', diceSides: 4 },
  //   { diceType: 'Power', diceSides: 6 },
  //   { diceType: 'Chaos', diceSides: 6 },
  // ],
  Young_Blood: [
    { diceType: 'Strength', diceSides: 4 },
    { diceType: 'Strength', diceSides: 6 },
    { diceType: 'Strength', diceSides: 8 },
    { diceType: 'Agility', diceSides: 10 },
    { diceType: 'Agility', diceSides: 20 },
    { diceType: 'Agility', diceSides: 100 },
    { diceType: 'Power', diceSides: 6 },
    { diceType: 'Chaos', diceSides: 8 },
    { diceType: 'Chaos', diceSides: 8 },
    { diceType: 'Chaos', diceSides: 8 },
    { diceType: 'Chaos', diceSides: 20 },
    { diceType: 'Chaos', diceSides: 100 },
    { diceType: 'Strength', diceSides: 4 },
    { diceType: 'Strength', diceSides: 6 },
    { diceType: 'Strength', diceSides: 8 },
    { diceType: 'Agility', diceSides: 10 },
    { diceType: 'Agility', diceSides: 20 },
    { diceType: 'Agility', diceSides: 100 },
    { diceType: 'Power', diceSides: 6 },
    { diceType: 'Chaos', diceSides: 8 },
    { diceType: 'Chaos', diceSides: 8 },
    { diceType: 'Chaos', diceSides: 8 },
    { diceType: 'Chaos', diceSides: 20 },
    { diceType: 'Chaos', diceSides: 100 },
  ],
}
